services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma

  api:
    build: ./api
    container_name: knowledge_api
    ports:
      - "8001:8001"
    depends_on:
      - ollama
      - chromadb

volumes:
  ollama_data:
  chroma_data:

## docker compose up --build -d
## docker exec -it knowledge_api python ingest.py
